# Generated by Django 5.2.17 on 2026-09-12 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRoleModel',
            fields=[
                ('slug', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mode', models.CharField(max_length=20)),
                ('default_model', models.CharField(max_length=200)),
                ('guidelines_md', models.TextField()),
            ],
            options={
                'db_table': 'agent_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('slug', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brief', models.TextField()),
                ('output_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log_tail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='teamsdb.projectmodel')),
            ],
            options={
                'db_table': 'run_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content_md', models.TextField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='teamsdb.agentrolemodel')),
            ],
            options={
                'db_table': 'skill',
                'ordering': ['role_id', 'name'],
                'unique_together': {('role', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='TeamMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teamsdb.projectmodel')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamsdb.agentrolemodel')),
            ],
            options={
                'db_table': 'team_member',
                'unique_together': {('project', 'role')},
            },
        ),
    ]
